In [2]:
# modules
import math

print(int(math.pow(2,3)))

8


In [4]:
from datetime import datetime

datetime.now()

datetime.datetime(2022, 6, 12, 15, 22, 0, 405347)

In [10]:
# to get all the functions available in the module
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [9]:
# to get the docstring of the module/function
math.__doc__

'This module provides access to the mathematical functions\ndefined by the C standard.'

In [28]:
# packages contain subpackages, subpackagaes contain modules

In [1]:
import numpy as np

In [4]:
# basic numpy arrays
a = np.array([1,2,3,4,5])
b = np.arange(0, 10, dtype=int)
print(a)
print(b)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
# dimensions
a.ndim

1

In [7]:
# shape of the array i.e rows, columns if rows are 1 then it is represented as (columns,) or columns are 1 then it is represented as (rows,)
a.shape

(5,)

In [35]:
# gives datatype of array
a.dtype

dtype('float64')

In [11]:
# 2D array
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2


In [12]:
# n dimensional array is called tensor.

In [19]:
# using arange (array range) (start, stop, stepsize)
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [18]:
# using linspace (linear space) (start, stop, number_of_points)
a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
# using ones
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
# using zeros
a = np.zeros((2,3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
# using eye (makes identity matrix)
a = np.eye(2, 3, dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0]])

In [28]:
# using diag (makes diagonal matrix, takes in a diagonal)
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
# random number arrays (uniform normal variables)
a = np.random.rand(4)
a

array([0.89151274, 0.34675207, 0.24029861, 0.65969172])

In [33]:
# random number arrays (standard normal variables)
a = np.random.randn(4)
a

array([1.40009423, 0.88743239, 1.0171084 , 0.83275519])

In [44]:
# indexing
a = np.arange(1, 10, 1, dtype=int)
print(a)
print(a[5])

b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(b)
print(b[2, 1]) # 10 (indexing in multidimensional arrays is slightly different than normal lists)

[1 2 3 4 5 6 7 8 9]
6
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10


In [47]:
# slicing (start : stop : stepsize)
a = np.arange(1, 10, 1, dtype=int)
print(a)
print(a[0:5:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5]


In [52]:
# combining indexing and slicing
a = np.arange(1, 10, 1)
b = np.arange(11, 15, 1)
print(a)
print(b)
a[5:] = b[::-1]
print(a)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14]
[ 1  2  3  4  5 14 13 12 11]


In [54]:
# mask function
a = np.random.randint(1, 10, 10)
print(a)

mask = (i % 2 == 0)

ex

[3 4 6 4 4 9 9 9 5 9]
